traducoes = {
    "id": "ID",
    "parent_id": "ID do Pai",
    "customer_id": "ID do Cliente",
    "shipping_class_id": "ID da Classe de Envio",
    
    "date_created": "Data de Criação",
    "date_created_gmt": "Data de Criação GMT",
    "date_modified": "Data de Modificação",
    "date_modified_gmt": "Data de Modificação GMT",
    "date_completed": "Data de Conclusão",
    "date_completed_gmt": "Data de Conclusão GMT",
    "date_paid": "Data de Pagamento",
    "date_paid_gmt": "Data de Pagamento GMT",
    "date_expires": "Data de Expiração",
    "date_expires_gmt": "Data de Expiração GMT",
    "date_on_sale_from": "Data de Início da Promoção",
    "date_on_sale_to": "Data de Fim da Promoção",
    
    "email": "E-mail",
    "first_name": "Nome",
    "last_name": "Sobrenome",
    "role": "Função",
    "username": "Nome de Usuário",
    "password": "Senha",
    "is_paying_customer": "Cliente Pagante",
    "avatar_url": "URL do Avatar",
    "customer_note": "Observação do Cliente",
    "customer_ip_address": "Endereço IP do Cliente",
    "customer_user_agent": "Navegador do Cliente",
    
    "billing": "Endereço de Cobrança",
    "shipping": "Endereço de Entrega",
    "country": "País",
    "state": "Estado",
    "postcode": "CEP",
    "postcodes": "CEPs",
    "city": "Cidade",
    "cities": "Cidades",
    
    "name": "Nome",
    "slug": "Slug",
    "permalink": "Link Permanente",
    "type": "Tipo",
    "status": "Status",
    "featured": "Destaque",
    "catalog_visibility": "Visibilidade no Catálogo",
    "description": "Descrição",
    "short_description": "Descrição Curta",
    "sku": "SKU",
    "price": "Preço",
    "regular_price": "Preço Regular",
    "sale_price": "Preço Promocional",
    "total_sales": "Total de Vendas",
    "virtual": "Virtual",
    "downloadable": "Baixável",
    "downloads": "Downloads",
    "download_limit": "Limite de Downloads",
    "download_expiry": "Expiração do Download",
    "external_url": "URL Externa",
    "button_text": "Texto do Botão",
    "tax_status": "Status de Imposto",
    "tax_class": "Classe de Imposto",
    "manage_stock": "Gerenciar Estoque",
    "stock_quantity": "Quantidade em Estoque",
    "stock_status": "Status do Estoque",
    "backorders": "Pedidos Pendentes",
    "backorders_allowed": "Pedidos Pendentes Permitidos",
    "backordered": "Em Pedido Pendente",
    "sold_individually": "Vendido Individualmente",
    "weight": "Peso",
    "dimensions": "Dimensões",
    "shipping_required": "Requer Envio",
    "shipping_taxable": "Envio Tributável",
    "shipping_class": "Classe de Envio",
    "reviews_allowed": "Avaliações Permitidas",
    "average_rating": "Avaliação Média",
    "rating_count": "Quantidade de Avaliações",
    
    "code": "Código",
    "amount": "Valor",
    "discount_type": "Tipo de Desconto",
    "usage_count": "Quantidade de Usos",
    "individual_use": "Uso Individual",
    "product_ids": "IDs dos Produtos",
    "excluded_product_ids": "IDs dos Produtos Excluídos",
    "usage_limit": "Limite de Uso",
    "usage_limit_per_user": "Limite de Uso por Usuário",
    "limit_usage_to_x_items": "Limitar Uso a X Itens",
    "free_shipping": "Frete Grátis",
    "product_categories": "Categorias de Produtos",
    "excluded_product_categories": "Categorias de Produtos Excluídas",
    "exclude_sale_items": "Excluir Itens em Promoção",
    "minimum_amount": "Valor Mínimo",
    "maximum_amount": "Valor Máximo",
    "email_restrictions": "Restrições de E-mail",
    "used_by": "Usado Por",
    
    "number": "Número",
    "order_key": "Chave do Pedido",
    "created_via": "Criado Via",
    "version": "Versão",
    "currency": "Moeda",
    "discount_total": "Total de Desconto",
    "discount_tax": "Imposto sobre Desconto",
    "shipping_total": "Total do Frete",
    "shipping_tax": "Imposto sobre Frete",
    "cart_tax": "Imposto do Carrinho",
    "total": "Total",
    "total_tax": "Total de Impostos",
    "prices_include_tax": "Preços Incluem Impostos",
    "transaction_id": "ID da Transação",
    "cart_hash": "Hash do Carrinho",
    "line_items": "Itens do Pedido",
    "tax_lines": "Linhas de Imposto",
    "shipping_lines": "Linhas de Frete",
    "fee_lines": "Linhas de Taxa",
    "coupon_lines": "Linhas de Cupom",
    "refunds": "Reembolsos",
    "set_paid": "Definir como Pago",
    
    "categories": "Categorias",
    "tags": "Tags",
    "attributes": "Atributos",
    
    "meta_data": "Metadados",
    "images": "Imagens",
    "variations": "Variações",
    "grouped_products": "Produtos Agrupados",
    "upsell_ids": "IDs de Venda Adicional",
    "cross_sell_ids": "IDs de Venda Cruzada",
    "purchase_note": "Nota de Compra",
    "menu_order": "Ordem no Menu"
}

