name: Build and Release WoocomerceDB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install textual
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onedir `
              --add-data "view/css;view/css" `
              --add-data "view/Woocommerce/css;view/Woocommerce/css" `
              --name WoocomerceDB 
              Main.py

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: WoocomerceDB
          path: dist/Main/*
